In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
from sklearn.model_selection import train_test_split

x = df.drop(["variety"], axis=1)
y = df["variety"]

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3, stratify=y)
X_train.head()

sepal.length  sepal.width  petal.length  petal.width
34            4.9          3.1           1.5          0.2
103           6.3          2.9           5.6          1.8
35            5.0          3.2           1.2          0.2
8             4.4          2.9           1.4          0.2
7             5.0          3.4           1.5          0.2

# Decision Tree (CART) no discretization

In [5]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

clf = tree.DecisionTreeClassifier()
y_pred = clf.fit(X_train, y_train).predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       1.00      1.00      1.00        15
   Virginica       1.00      1.00      1.00        15

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

1.0


# Проводим дискретизацию признаков

In [6]:
from sklearn.preprocessing import KBinsDiscretizer  
from sklearn.preprocessing import StandardScaler

est = KBinsDiscretizer(n_bins=13, encode='ordinal', strategy='uniform')

# X_train['rssiOne'] = X_train.iloc[:,1].values.reshape(6102,1)
# X_train['rssiTwo'] = X_train.iloc[:,2].values.reshape(6102,1)
# X_test['rssiOne'] = X_test.iloc[:,1].values.reshape(2616,1)
# X_test['rssiTwo'] = X_test.iloc[:,2].values.reshape(2616,1)

scaler = StandardScaler()
scaler.fit(X_train, y_train)
X_train_real_scaled = scaler.transform(X_train)
X_test_real_scaled = scaler.transform(X_test)

# X_train['rssiOne']
est.fit(X_train) 
Xtr = est.transform(X_train)
# X_train

Xtst = est.transform(X_test)
Xtst

array([[ 7.,  5.,  9.,  9.],
       [ 1.,  5.,  0.,  1.],
       [ 2.,  8.,  0.,  1.],
       [ 8.,  5.,  9., 11.],
       [ 3.,  9.,  1.,  0.],
       [ 2.,  7.,  1.,  2.],
       [11.,  5., 12., 10.],
       [10.,  8., 11., 12.],
       [ 2.,  8.,  0.,  1.],
       [ 5.,  5.,  9.,  9.],
       [ 4.,  3.,  7.,  6.],
       [ 5.,  3.,  9.,  9.],
       [11.,  4., 11.,  9.],
       [ 8.,  4.,  7.,  6.],
       [ 1.,  5.,  0.,  0.],
       [ 7.,  7., 10., 12.],
       [12.,  5., 11., 11.],
       [ 4.,  2.,  6.,  5.],
       [ 3.,  8.,  1.,  0.],
       [ 3.,  7.,  1.,  0.],
       [ 4.,  5.,  7.,  7.],
       [10.,  6., 11.,  9.],
       [ 9.,  6.,  8.,  7.],
       [ 3., 10.,  0.,  1.],
       [ 6.,  7.,  7.,  8.],
       [ 5.,  5.,  7.,  5.],
       [ 9.,  5.,  9., 10.],
       [ 5.,  3.,  6.,  5.],
       [ 3.,  7.,  0.,  0.],
       [10.,  5., 10., 10.],
       [ 7.,  4.,  7.,  6.],
       [ 5.,  3.,  9.,  9.],
       [ 6.,  4.,  6.,  6.],
       [ 3.,  5.,  7.,  7.],
       [ 3.,  

# Алгоритм Деревьев решений после дискретизации

In [7]:
clf = tree.DecisionTreeClassifier()
y_pred = clf.fit(Xtr, y_train).predict(Xtst)

# summarize the fit of the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[15  0  0]
 [ 0 14  1]
 [ 0  0 15]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       1.00      0.93      0.97        15
   Virginica       0.94      1.00      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777
