In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
from sklearn.model_selection import train_test_split

x = df.drop(["variety"], axis=1)
y = df["variety"]

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3, stratify=y)
X_train.head()

sepal.length  sepal.width  petal.length  petal.width
146           6.3          2.5           5.0          1.9
40            5.0          3.5           1.3          0.3
122           7.7          2.8           6.7          2.0
103           6.3          2.9           5.6          1.8
144           6.7          3.3           5.7          2.5

# Naive Bayes

In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       0.94      1.00      0.97        15
   Virginica       1.00      0.93      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777


# Проводим дискретизацию признаков


In [7]:
from sklearn.preprocessing import KBinsDiscretizer  
from sklearn.preprocessing import StandardScaler

est = KBinsDiscretizer(n_bins=13, encode='ordinal', strategy='uniform')

# X_train['rssiOne'] = X_train.iloc[:,1].values.reshape(6102,1)
# X_train['rssiTwo'] = X_train.iloc[:,2].values.reshape(6102,1)
# X_test['rssiOne'] = X_test.iloc[:,1].values.reshape(2616,1)
# X_test['rssiTwo'] = X_test.iloc[:,2].values.reshape(2616,1)

scaler = StandardScaler()
scaler.fit(X_train, y_train)
X_train_real_scaled = scaler.transform(X_train)
X_test_real_scaled = scaler.transform(X_test)

# X_train['rssiOne']
est.fit(X_train) 
Xtr = est.transform(X_train)
# X_train

Xtst = est.transform(X_test)
Xtst

array([[12.,  9., 12., 11.],
       [ 2.,  2.,  5.,  4.],
       [ 2.,  8.,  1.,  2.],
       [ 8.,  4.,  7.,  6.],
       [ 2.,  9.,  1.,  1.],
       [ 1.,  5.,  1.,  0.],
       [ 5.,  3.,  6.,  4.],
       [ 9.,  5.,  9., 10.],
       [ 5.,  2.,  8., 10.],
       [10.,  8., 11., 12.],
       [ 6.,  5.,  7.,  7.],
       [ 3.,  9.,  1.,  0.],
       [ 7.,  4., 10., 10.],
       [ 6.,  5.,  8.,  9.],
       [ 3.,  9.,  1.,  0.],
       [ 2.,  5.,  1.,  0.],
       [10.,  5., 10.,  8.],
       [ 8.,  5.,  8.,  7.],
       [ 7.,  5., 10., 11.],
       [ 2.,  7.,  0.,  0.],
       [ 4.,  2.,  6.,  5.],
       [ 4.,  3.,  7.,  6.],
       [10.,  4., 11.,  9.],
       [ 3., 10.,  1.,  1.],
       [ 5.,  5.,  9.,  9.],
       [ 7.,  2.,  8.,  7.],
       [ 1.,  6.,  0.,  0.],
       [ 5.,  3.,  6.,  5.],
       [ 4.,  2.,  5.,  4.],
       [ 6.,  3.,  9.,  8.],
       [ 4.,  2.,  6.,  6.],
       [ 7.,  4.,  9.,  7.],
       [ 5.,  3.,  5.,  4.],
       [ 1.,  5.,  1.,  0.],
       [ 7.,  

# Naive Bayes после дискретизации

In [8]:
gnb = GaussianNB()
y_pred = gnb.fit(Xtr, y_train).predict(Xtst)

# summarize the fit of the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[15  0  0]
 [ 0 13  2]
 [ 0  1 14]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       0.93      0.87      0.90        15
   Virginica       0.88      0.93      0.90        15

   micro avg       0.93      0.93      0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

0.9333333333333333
